- name: sudo apt update
  apt:
    update_cache: yes

- name: install docker_packages
  apt:
    name: "{{docker_packages}}"
    state: present
  vars:
    docker_packages:
      - ca-certificates 
      - curl
      - gnupg
      - lsb-release

- name: create directory for keyring
  file:
    path: /etc/apt/keyrings
    state: directory

- name: download and import gpg into keyring
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      keyring: /etc/apt/keyrings/docker.gpg

- name: architecture of server
  shell: echo "$(dpkg --print-architecture)"
  register: architecture

- name: Display architecture
  debug:
    var: architecture.stdout

- name: Added  docker.list
  # shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  copy:
    dest: /etc/apt/sources.list.d/docker.list 
    content: | 
      deb [arch={{architecture.stdout}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: if error occur duting apt update 
  shell: sudo chmod a+r /etc/apt/keyrings/docker.gpg


- name: install docker, docker cli, containerd.io and docker compose 
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: start docker service
  service:
    name: docker.service
    state: started
    enabled: yes